# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f336dd1c6728ce0ecb8e7140882c369fd88135d601fd2bdffe44ef6f920db6a0f25a911a7420d08709b2272faac913639fd50cde5308e50b12c646c4b877994

test:
  secret_key_base: 2a20338789e694d6c7ebb8197900351b6569725a9543f300f88d9680c520205a4f07c6f99616a6bb000769f25ce025f319bc16e9fd498a4a1a7c24b70392f948

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
